### ISSUE TITLE
Filter multiple tilesets

### ISSUE THREAD

**Issue by nerik** [Vizzuality/GlobalFishingWatch#678] opened 2017-08-03 10:47 UTC
https://airtable.com/tbliFUBZhHrWTVy5I/viwjB6S36hfjUz7EU/recYj8gUr6WH58yF1

**Comment by tiagojsag** [comment] 2017-08-08 15:59
duplicate of https://github.com/Vizzuality/GlobalFishingWatch/issues/661

**Closed by tiagojsag** 2017-08-08 15:59 UTC
Labels: Epic, Workshop proceeding (AirTable)
